# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Improbably Easier than Recipe Cards
email: mattsugihara@gmail.com
twitter_username: mattsugihara
github_username:  mattsugihara
permalink: :title/
baseurl: /recipes

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

sass:
  load_paths:
    - _includes
    - _layouts

# this makes each post use the post layout
defaults:
 -
    scope:
      path: ""
    values:
      layout: "recipe"